# Generated by Django 4.2.6 on 2023-10-05 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParcelLocker',
            fields=[
                ('locker_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('locker_location_address', models.CharField(max_length=50)),
                ('locker_size', models.CharField(choices=[('XS', 'Extra Small'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large')], max_length=2)),
                ('status', models.CharField(choices=[('F', 'Free'), ('B', 'Busy'), ('OOO', 'Out Of Order')], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Parcel',
            fields=[
                ('parcel_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('sender', models.CharField(max_length=50)),
                ('sender_email', models.CharField(max_length=50)),
                ('sender_phone', models.CharField(max_length=50)),
                ('receiver', models.CharField(max_length=50)),
                ('receiver_phone', models.CharField(max_length=50)),
                ('parcel_size', models.CharField(choices=[('XS', 'Extra Small'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large')], max_length=2)),
                ('lockerID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ParcelService.parcellocker')),
            ],
        ),
    ]
